parameters:
    models: MMP
    similarity: Cosine
    alpha: [0, 0.1, 1]
    batch_size: [32]
    corruption: [0.2, 0.3, 0.4, 0.5]
    epoch: [300]
    iteration: [10]
    key_dimension: [3]
    lambda: [0.001, 0.0001, 0.00001, 0.000001]
    learning_rate: [0.00005, 0.0001, 0.0005]
    mode_dimension: [4]
    rank: [40]
    root: [0.9, 1.0, 1.1]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall]
