parameters:
    models: MMP
    similarity: Cosine
    alpha: [0, 0.1, 1, 10]
    batch_size: [32]
    corruption: [0.2, 0.3, 0.4]
    epoch: [30, 300]
    iteration: [10]
    key_dimension: [3, 4, 5]
    lambda: [0.0001, 0.00001, 0.000001]
    learning_rate: [0.0001, 0.001]
    mode_dimension: [1, 3, 5]
    rank: [40]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall]
