parameters:
    models: ACF
    similarity: Cosine
    alpha: [1]
    batch_size: [512]
    corruption: [0]
    epoch: [1]
    iteration: [10]
    key_dimension: [3, 4, 5]
    lambda: [0.00001, 0.0001, 0.001]
    learning_rate: [0.0001]
    rank: [100, 200, 300]
    mode_dimension: [1]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall]
