parameters:
    models: MMP
    similarity: Cosine
    alpha: [0, 0.1, 1]
    batch_size: [32]
    corruption: [0.4, 0.3]
    epoch: [300]
    iteration: [10]
    key_dimension: [3, 4, 5]
    lambda: [0.001, 0.01, 0.0001]
    learning_rate: [0.00001]
    mode_dimension: [5]
    rank: [100, 150, 200]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall]
