parameters:
    models: MMP
    similarity: Cosine
    alpha: [0, 0.1, 1]
    batch_size: [32]
    corruption: [0.2, 0.3, 0.4]
    epoch: [300]
    iteration: [10]
    key_dimension: [3]
    lambda: [0.00001]
    learning_rate: [0.00005]
    mode_dimension: [5]
    rank: [100]
    root: [1.0]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall]