#!/usr/bin/env bash
cd ~/git/MultiModesPreferenceEstimation
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part1.csv --parameters config/amazon/digital_music/mmp-part1.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part2.csv --parameters config/amazon/digital_music/mmp-part2.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part3.csv --parameters config/amazon/digital_music/mmp-part3.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part4.csv --parameters config/amazon/digital_music/mmp-part4.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part5.csv --parameters config/amazon/digital_music/mmp-part5.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part6.csv --parameters config/amazon/digital_music/mmp-part6.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part7.csv --parameters config/amazon/digital_music/mmp-part7.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part8.csv --parameters config/amazon/digital_music/mmp-part8.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part9.csv --parameters config/amazon/digital_music/mmp-part9.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part10.csv --parameters config/amazon/digital_music/mmp-part10.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part11.csv --parameters config/amazon/digital_music/mmp-part11.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part12.csv --parameters config/amazon/digital_music/mmp-part12.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part13.csv --parameters config/amazon/digital_music/mmp-part13.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part14.csv --parameters config/amazon/digital_music/mmp-part14.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part15.csv --parameters config/amazon/digital_music/mmp-part15.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part16.csv --parameters config/amazon/digital_music/mmp-part16.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part17.csv --parameters config/amazon/digital_music/mmp-part17.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part18.csv --parameters config/amazon/digital_music/mmp-part18.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part19.csv --parameters config/amazon/digital_music/mmp-part19.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part20.csv --parameters config/amazon/digital_music/mmp-part20.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part21.csv --parameters config/amazon/digital_music/mmp-part21.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part22.csv --parameters config/amazon/digital_music/mmp-part22.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part23.csv --parameters config/amazon/digital_music/mmp-part23.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part24.csv --parameters config/amazon/digital_music/mmp-part24.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part25.csv --parameters config/amazon/digital_music/mmp-part25.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part26.csv --parameters config/amazon/digital_music/mmp-part26.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part27.csv --parameters config/amazon/digital_music/mmp-part27.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part28.csv --parameters config/amazon/digital_music/mmp-part28.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part29.csv --parameters config/amazon/digital_music/mmp-part29.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part30.csv --parameters config/amazon/digital_music/mmp-part30.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part31.csv --parameters config/amazon/digital_music/mmp-part31.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part32.csv --parameters config/amazon/digital_music/mmp-part32.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part33.csv --parameters config/amazon/digital_music/mmp-part33.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part34.csv --parameters config/amazon/digital_music/mmp-part34.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part35.csv --parameters config/amazon/digital_music/mmp-part35.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part36.csv --parameters config/amazon/digital_music/mmp-part36.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part37.csv --parameters config/amazon/digital_music/mmp-part37.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part38.csv --parameters config/amazon/digital_music/mmp-part38.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part39.csv --parameters config/amazon/digital_music/mmp-part39.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part40.csv --parameters config/amazon/digital_music/mmp-part40.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part41.csv --parameters config/amazon/digital_music/mmp-part41.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part42.csv --parameters config/amazon/digital_music/mmp-part42.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part43.csv --parameters config/amazon/digital_music/mmp-part43.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part44.csv --parameters config/amazon/digital_music/mmp-part44.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part45.csv --parameters config/amazon/digital_music/mmp-part45.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part46.csv --parameters config/amazon/digital_music/mmp-part46.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part47.csv --parameters config/amazon/digital_music/mmp-part47.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part48.csv --parameters config/amazon/digital_music/mmp-part48.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part49.csv --parameters config/amazon/digital_music/mmp-part49.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part50.csv --parameters config/amazon/digital_music/mmp-part50.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part51.csv --parameters config/amazon/digital_music/mmp-part51.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part52.csv --parameters config/amazon/digital_music/mmp-part52.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part53.csv --parameters config/amazon/digital_music/mmp-part53.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part54.csv --parameters config/amazon/digital_music/mmp-part54.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part55.csv --parameters config/amazon/digital_music/mmp-part55.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part56.csv --parameters config/amazon/digital_music/mmp-part56.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part57.csv --parameters config/amazon/digital_music/mmp-part57.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part58.csv --parameters config/amazon/digital_music/mmp-part58.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part59.csv --parameters config/amazon/digital_music/mmp-part59.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part60.csv --parameters config/amazon/digital_music/mmp-part60.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part61.csv --parameters config/amazon/digital_music/mmp-part61.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part62.csv --parameters config/amazon/digital_music/mmp-part62.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part63.csv --parameters config/amazon/digital_music/mmp-part63.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part64.csv --parameters config/amazon/digital_music/mmp-part64.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part65.csv --parameters config/amazon/digital_music/mmp-part65.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part66.csv --parameters config/amazon/digital_music/mmp-part66.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part67.csv --parameters config/amazon/digital_music/mmp-part67.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part68.csv --parameters config/amazon/digital_music/mmp-part68.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part69.csv --parameters config/amazon/digital_music/mmp-part69.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part70.csv --parameters config/amazon/digital_music/mmp-part70.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part71.csv --parameters config/amazon/digital_music/mmp-part71.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part72.csv --parameters config/amazon/digital_music/mmp-part72.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part73.csv --parameters config/amazon/digital_music/mmp-part73.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part74.csv --parameters config/amazon/digital_music/mmp-part74.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part75.csv --parameters config/amazon/digital_music/mmp-part75.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part76.csv --parameters config/amazon/digital_music/mmp-part76.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part77.csv --parameters config/amazon/digital_music/mmp-part77.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part78.csv --parameters config/amazon/digital_music/mmp-part78.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part79.csv --parameters config/amazon/digital_music/mmp-part79.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part80.csv --parameters config/amazon/digital_music/mmp-part80.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part81.csv --parameters config/amazon/digital_music/mmp-part81.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part82.csv --parameters config/amazon/digital_music/mmp-part82.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part83.csv --parameters config/amazon/digital_music/mmp-part83.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part84.csv --parameters config/amazon/digital_music/mmp-part84.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part85.csv --parameters config/amazon/digital_music/mmp-part85.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part86.csv --parameters config/amazon/digital_music/mmp-part86.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part87.csv --parameters config/amazon/digital_music/mmp-part87.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part88.csv --parameters config/amazon/digital_music/mmp-part88.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part89.csv --parameters config/amazon/digital_music/mmp-part89.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part90.csv --parameters config/amazon/digital_music/mmp-part90.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part91.csv --parameters config/amazon/digital_music/mmp-part91.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part92.csv --parameters config/amazon/digital_music/mmp-part92.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part93.csv --parameters config/amazon/digital_music/mmp-part93.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part94.csv --parameters config/amazon/digital_music/mmp-part94.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part95.csv --parameters config/amazon/digital_music/mmp-part95.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part96.csv --parameters config/amazon/digital_music/mmp-part96.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part97.csv --parameters config/amazon/digital_music/mmp-part97.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part98.csv --parameters config/amazon/digital_music/mmp-part98.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part99.csv --parameters config/amazon/digital_music/mmp-part99.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part100.csv --parameters config/amazon/digital_music/mmp-part100.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part101.csv --parameters config/amazon/digital_music/mmp-part101.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part102.csv --parameters config/amazon/digital_music/mmp-part102.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part103.csv --parameters config/amazon/digital_music/mmp-part103.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part104.csv --parameters config/amazon/digital_music/mmp-part104.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part105.csv --parameters config/amazon/digital_music/mmp-part105.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part106.csv --parameters config/amazon/digital_music/mmp-part106.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part107.csv --parameters config/amazon/digital_music/mmp-part107.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part108.csv --parameters config/amazon/digital_music/mmp-part108.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part109.csv --parameters config/amazon/digital_music/mmp-part109.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part110.csv --parameters config/amazon/digital_music/mmp-part110.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part111.csv --parameters config/amazon/digital_music/mmp-part111.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part112.csv --parameters config/amazon/digital_music/mmp-part112.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part113.csv --parameters config/amazon/digital_music/mmp-part113.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part114.csv --parameters config/amazon/digital_music/mmp-part114.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part115.csv --parameters config/amazon/digital_music/mmp-part115.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part116.csv --parameters config/amazon/digital_music/mmp-part116.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part117.csv --parameters config/amazon/digital_music/mmp-part117.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part118.csv --parameters config/amazon/digital_music/mmp-part118.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part119.csv --parameters config/amazon/digital_music/mmp-part119.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part120.csv --parameters config/amazon/digital_music/mmp-part120.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part121.csv --parameters config/amazon/digital_music/mmp-part121.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part122.csv --parameters config/amazon/digital_music/mmp-part122.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part123.csv --parameters config/amazon/digital_music/mmp-part123.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part124.csv --parameters config/amazon/digital_music/mmp-part124.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part125.csv --parameters config/amazon/digital_music/mmp-part125.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part126.csv --parameters config/amazon/digital_music/mmp-part126.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part127.csv --parameters config/amazon/digital_music/mmp-part127.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part128.csv --parameters config/amazon/digital_music/mmp-part128.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part129.csv --parameters config/amazon/digital_music/mmp-part129.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part130.csv --parameters config/amazon/digital_music/mmp-part130.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part131.csv --parameters config/amazon/digital_music/mmp-part131.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part132.csv --parameters config/amazon/digital_music/mmp-part132.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part133.csv --parameters config/amazon/digital_music/mmp-part133.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part134.csv --parameters config/amazon/digital_music/mmp-part134.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part135.csv --parameters config/amazon/digital_music/mmp-part135.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part136.csv --parameters config/amazon/digital_music/mmp-part136.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part137.csv --parameters config/amazon/digital_music/mmp-part137.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part138.csv --parameters config/amazon/digital_music/mmp-part138.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part139.csv --parameters config/amazon/digital_music/mmp-part139.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part140.csv --parameters config/amazon/digital_music/mmp-part140.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part141.csv --parameters config/amazon/digital_music/mmp-part141.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part142.csv --parameters config/amazon/digital_music/mmp-part142.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part143.csv --parameters config/amazon/digital_music/mmp-part143.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part144.csv --parameters config/amazon/digital_music/mmp-part144.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part145.csv --parameters config/amazon/digital_music/mmp-part145.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part146.csv --parameters config/amazon/digital_music/mmp-part146.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part147.csv --parameters config/amazon/digital_music/mmp-part147.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part148.csv --parameters config/amazon/digital_music/mmp-part148.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part149.csv --parameters config/amazon/digital_music/mmp-part149.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part150.csv --parameters config/amazon/digital_music/mmp-part150.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part151.csv --parameters config/amazon/digital_music/mmp-part151.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part152.csv --parameters config/amazon/digital_music/mmp-part152.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part153.csv --parameters config/amazon/digital_music/mmp-part153.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part154.csv --parameters config/amazon/digital_music/mmp-part154.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part155.csv --parameters config/amazon/digital_music/mmp-part155.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part156.csv --parameters config/amazon/digital_music/mmp-part156.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part157.csv --parameters config/amazon/digital_music/mmp-part157.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part158.csv --parameters config/amazon/digital_music/mmp-part158.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part159.csv --parameters config/amazon/digital_music/mmp-part159.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part160.csv --parameters config/amazon/digital_music/mmp-part160.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part161.csv --parameters config/amazon/digital_music/mmp-part161.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part162.csv --parameters config/amazon/digital_music/mmp-part162.yml
