#!/usr/bin/env bash
cd ~/git/MultiModesPreferenceEstimation
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part163.csv --parameters config/amazon/digital_music/mmp-part163.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part164.csv --parameters config/amazon/digital_music/mmp-part164.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part165.csv --parameters config/amazon/digital_music/mmp-part165.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part166.csv --parameters config/amazon/digital_music/mmp-part166.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part167.csv --parameters config/amazon/digital_music/mmp-part167.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part168.csv --parameters config/amazon/digital_music/mmp-part168.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part169.csv --parameters config/amazon/digital_music/mmp-part169.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part170.csv --parameters config/amazon/digital_music/mmp-part170.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part171.csv --parameters config/amazon/digital_music/mmp-part171.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part172.csv --parameters config/amazon/digital_music/mmp-part172.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part173.csv --parameters config/amazon/digital_music/mmp-part173.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part174.csv --parameters config/amazon/digital_music/mmp-part174.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part175.csv --parameters config/amazon/digital_music/mmp-part175.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part176.csv --parameters config/amazon/digital_music/mmp-part176.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part177.csv --parameters config/amazon/digital_music/mmp-part177.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part178.csv --parameters config/amazon/digital_music/mmp-part178.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part179.csv --parameters config/amazon/digital_music/mmp-part179.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part180.csv --parameters config/amazon/digital_music/mmp-part180.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part181.csv --parameters config/amazon/digital_music/mmp-part181.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part182.csv --parameters config/amazon/digital_music/mmp-part182.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part183.csv --parameters config/amazon/digital_music/mmp-part183.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part184.csv --parameters config/amazon/digital_music/mmp-part184.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part185.csv --parameters config/amazon/digital_music/mmp-part185.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part186.csv --parameters config/amazon/digital_music/mmp-part186.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part187.csv --parameters config/amazon/digital_music/mmp-part187.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part188.csv --parameters config/amazon/digital_music/mmp-part188.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part189.csv --parameters config/amazon/digital_music/mmp-part189.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part190.csv --parameters config/amazon/digital_music/mmp-part190.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part191.csv --parameters config/amazon/digital_music/mmp-part191.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part192.csv --parameters config/amazon/digital_music/mmp-part192.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part193.csv --parameters config/amazon/digital_music/mmp-part193.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part194.csv --parameters config/amazon/digital_music/mmp-part194.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part195.csv --parameters config/amazon/digital_music/mmp-part195.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part196.csv --parameters config/amazon/digital_music/mmp-part196.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part197.csv --parameters config/amazon/digital_music/mmp-part197.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part198.csv --parameters config/amazon/digital_music/mmp-part198.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part199.csv --parameters config/amazon/digital_music/mmp-part199.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part200.csv --parameters config/amazon/digital_music/mmp-part200.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part201.csv --parameters config/amazon/digital_music/mmp-part201.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part202.csv --parameters config/amazon/digital_music/mmp-part202.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part203.csv --parameters config/amazon/digital_music/mmp-part203.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part204.csv --parameters config/amazon/digital_music/mmp-part204.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part205.csv --parameters config/amazon/digital_music/mmp-part205.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part206.csv --parameters config/amazon/digital_music/mmp-part206.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part207.csv --parameters config/amazon/digital_music/mmp-part207.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part208.csv --parameters config/amazon/digital_music/mmp-part208.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part209.csv --parameters config/amazon/digital_music/mmp-part209.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part210.csv --parameters config/amazon/digital_music/mmp-part210.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part211.csv --parameters config/amazon/digital_music/mmp-part211.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part212.csv --parameters config/amazon/digital_music/mmp-part212.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part213.csv --parameters config/amazon/digital_music/mmp-part213.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part214.csv --parameters config/amazon/digital_music/mmp-part214.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part215.csv --parameters config/amazon/digital_music/mmp-part215.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part216.csv --parameters config/amazon/digital_music/mmp-part216.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part217.csv --parameters config/amazon/digital_music/mmp-part217.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part218.csv --parameters config/amazon/digital_music/mmp-part218.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part219.csv --parameters config/amazon/digital_music/mmp-part219.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part220.csv --parameters config/amazon/digital_music/mmp-part220.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part221.csv --parameters config/amazon/digital_music/mmp-part221.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part222.csv --parameters config/amazon/digital_music/mmp-part222.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part223.csv --parameters config/amazon/digital_music/mmp-part223.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part224.csv --parameters config/amazon/digital_music/mmp-part224.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part225.csv --parameters config/amazon/digital_music/mmp-part225.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part226.csv --parameters config/amazon/digital_music/mmp-part226.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part227.csv --parameters config/amazon/digital_music/mmp-part227.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part228.csv --parameters config/amazon/digital_music/mmp-part228.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part229.csv --parameters config/amazon/digital_music/mmp-part229.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part230.csv --parameters config/amazon/digital_music/mmp-part230.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part231.csv --parameters config/amazon/digital_music/mmp-part231.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part232.csv --parameters config/amazon/digital_music/mmp-part232.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part233.csv --parameters config/amazon/digital_music/mmp-part233.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part234.csv --parameters config/amazon/digital_music/mmp-part234.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part235.csv --parameters config/amazon/digital_music/mmp-part235.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part236.csv --parameters config/amazon/digital_music/mmp-part236.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part237.csv --parameters config/amazon/digital_music/mmp-part237.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part238.csv --parameters config/amazon/digital_music/mmp-part238.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part239.csv --parameters config/amazon/digital_music/mmp-part239.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part240.csv --parameters config/amazon/digital_music/mmp-part240.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part241.csv --parameters config/amazon/digital_music/mmp-part241.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part242.csv --parameters config/amazon/digital_music/mmp-part242.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part243.csv --parameters config/amazon/digital_music/mmp-part243.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part244.csv --parameters config/amazon/digital_music/mmp-part244.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part245.csv --parameters config/amazon/digital_music/mmp-part245.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part246.csv --parameters config/amazon/digital_music/mmp-part246.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part247.csv --parameters config/amazon/digital_music/mmp-part247.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part248.csv --parameters config/amazon/digital_music/mmp-part248.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part249.csv --parameters config/amazon/digital_music/mmp-part249.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part250.csv --parameters config/amazon/digital_music/mmp-part250.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part251.csv --parameters config/amazon/digital_music/mmp-part251.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part252.csv --parameters config/amazon/digital_music/mmp-part252.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part253.csv --parameters config/amazon/digital_music/mmp-part253.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part254.csv --parameters config/amazon/digital_music/mmp-part254.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part255.csv --parameters config/amazon/digital_music/mmp-part255.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part256.csv --parameters config/amazon/digital_music/mmp-part256.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part257.csv --parameters config/amazon/digital_music/mmp-part257.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part258.csv --parameters config/amazon/digital_music/mmp-part258.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part259.csv --parameters config/amazon/digital_music/mmp-part259.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part260.csv --parameters config/amazon/digital_music/mmp-part260.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part261.csv --parameters config/amazon/digital_music/mmp-part261.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part262.csv --parameters config/amazon/digital_music/mmp-part262.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part263.csv --parameters config/amazon/digital_music/mmp-part263.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part264.csv --parameters config/amazon/digital_music/mmp-part264.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part265.csv --parameters config/amazon/digital_music/mmp-part265.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part266.csv --parameters config/amazon/digital_music/mmp-part266.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part267.csv --parameters config/amazon/digital_music/mmp-part267.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part268.csv --parameters config/amazon/digital_music/mmp-part268.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part269.csv --parameters config/amazon/digital_music/mmp-part269.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part270.csv --parameters config/amazon/digital_music/mmp-part270.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part271.csv --parameters config/amazon/digital_music/mmp-part271.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part272.csv --parameters config/amazon/digital_music/mmp-part272.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part273.csv --parameters config/amazon/digital_music/mmp-part273.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part274.csv --parameters config/amazon/digital_music/mmp-part274.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part275.csv --parameters config/amazon/digital_music/mmp-part275.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part276.csv --parameters config/amazon/digital_music/mmp-part276.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part277.csv --parameters config/amazon/digital_music/mmp-part277.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part278.csv --parameters config/amazon/digital_music/mmp-part278.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part279.csv --parameters config/amazon/digital_music/mmp-part279.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part280.csv --parameters config/amazon/digital_music/mmp-part280.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part281.csv --parameters config/amazon/digital_music/mmp-part281.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part282.csv --parameters config/amazon/digital_music/mmp-part282.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part283.csv --parameters config/amazon/digital_music/mmp-part283.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part284.csv --parameters config/amazon/digital_music/mmp-part284.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part285.csv --parameters config/amazon/digital_music/mmp-part285.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part286.csv --parameters config/amazon/digital_music/mmp-part286.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part287.csv --parameters config/amazon/digital_music/mmp-part287.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part288.csv --parameters config/amazon/digital_music/mmp-part288.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part289.csv --parameters config/amazon/digital_music/mmp-part289.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part290.csv --parameters config/amazon/digital_music/mmp-part290.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part291.csv --parameters config/amazon/digital_music/mmp-part291.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part292.csv --parameters config/amazon/digital_music/mmp-part292.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part293.csv --parameters config/amazon/digital_music/mmp-part293.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part294.csv --parameters config/amazon/digital_music/mmp-part294.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part295.csv --parameters config/amazon/digital_music/mmp-part295.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part296.csv --parameters config/amazon/digital_music/mmp-part296.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part297.csv --parameters config/amazon/digital_music/mmp-part297.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part298.csv --parameters config/amazon/digital_music/mmp-part298.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part299.csv --parameters config/amazon/digital_music/mmp-part299.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part300.csv --parameters config/amazon/digital_music/mmp-part300.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part301.csv --parameters config/amazon/digital_music/mmp-part301.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part302.csv --parameters config/amazon/digital_music/mmp-part302.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part303.csv --parameters config/amazon/digital_music/mmp-part303.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part304.csv --parameters config/amazon/digital_music/mmp-part304.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part305.csv --parameters config/amazon/digital_music/mmp-part305.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part306.csv --parameters config/amazon/digital_music/mmp-part306.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part307.csv --parameters config/amazon/digital_music/mmp-part307.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part308.csv --parameters config/amazon/digital_music/mmp-part308.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part309.csv --parameters config/amazon/digital_music/mmp-part309.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part310.csv --parameters config/amazon/digital_music/mmp-part310.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part311.csv --parameters config/amazon/digital_music/mmp-part311.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part312.csv --parameters config/amazon/digital_music/mmp-part312.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part313.csv --parameters config/amazon/digital_music/mmp-part313.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part314.csv --parameters config/amazon/digital_music/mmp-part314.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part315.csv --parameters config/amazon/digital_music/mmp-part315.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part316.csv --parameters config/amazon/digital_music/mmp-part316.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part317.csv --parameters config/amazon/digital_music/mmp-part317.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part318.csv --parameters config/amazon/digital_music/mmp-part318.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part319.csv --parameters config/amazon/digital_music/mmp-part319.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part320.csv --parameters config/amazon/digital_music/mmp-part320.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part321.csv --parameters config/amazon/digital_music/mmp-part321.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part322.csv --parameters config/amazon/digital_music/mmp-part322.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part323.csv --parameters config/amazon/digital_music/mmp-part323.yml
python tune_parameters.py --data-dir data/amazon/digital_music/ --save-path amazon/digital_music/tuning_general/mmp-part324.csv --parameters config/amazon/digital_music/mmp-part324.yml
